"""
Train the TransactionCategorizer on synthetic labeled data.

Run once before using categorize_node:
    cd agentledger/
    python scripts/train_categorizer.py

Saves model to: models/categorizer.pkl
Target accuracy: 85%+ (RF baseline) on holdout set.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from agentledger.ml.categorizer import TransactionCategorizer
from agentledger.schemas.models import Transaction

# ---------------------------------------------------------------------------
# Synthetic labeled training data
# Each entry: (merchant_name, description, category_label)
# 30+ examples per category = ~540 total samples for TF-IDF to work well.
# ---------------------------------------------------------------------------

RAW_LABELS: list[tuple[str, str, str]] = [
    # income_salary
    ("EMPLOYER PAYROLL",       "Direct deposit payroll",          "income_salary"),
    ("ADP PAYROLL",            "ADP payroll deposit",             "income_salary"),
    ("GUSTO PAYROLL",          "Gusto payroll",                   "income_salary"),
    ("COMPANY INC PAYROLL",    "Salary deposit",                  "income_salary"),
    ("DIRECT DEPOSIT",         "Direct deposit salary",           "income_salary"),
    ("PAYROLL DEPOSIT",        "Payroll direct deposit",          "income_salary"),
    ("EMPLOYER DIRECT",        "Employer direct deposit",         "income_salary"),
    ("BIWEEKLY PAYROLL",       "Biweekly salary payment",         "income_salary"),
    ("HR PAYROLL CORP",        "HR payroll corporation",          "income_salary"),
    ("SALARY CREDIT",          "Monthly salary credit",           "income_salary"),
    ("PAYCHECK DEPOSIT",       "Paycheck deposit",                "income_salary"),
    ("W2 INCOME DEPOSIT",      "W2 employer income",              "income_salary"),
    ("STAFFING AGENCY PAY",    "Staffing agency payroll",         "income_salary"),
    ("CORPORATE PAYROLL",      "Corporate salary deposit",        "income_salary"),
    ("COMPANY SALARY",         "Company salary transfer",         "income_salary"),
    ("WAGES DIRECT DEPOSIT",   "Wages direct deposit",            "income_salary"),
    ("SEMI MONTHLY PAYROLL",   "Semi-monthly payroll",            "income_salary"),
    ("EMPLOYER WAGES",         "Employer wages deposit",          "income_salary"),
    ("PAYROLL ACH",            "Payroll ACH transfer",            "income_salary"),
    ("FIRM SALARY DEPOSIT",    "Firm salary deposit",             "income_salary"),
    ("NET PAY DEPOSIT",        "Net pay deposit",                 "income_salary"),
    ("INCOME DIRECT DEPOSIT",  "Income direct deposit",           "income_salary"),
    ("SALARY PAYMENT",         "Salary payment received",         "income_salary"),
    ("WORK INCOME DEPOSIT",    "Work income deposit",             "income_salary"),
    ("FULL TIME SALARY",       "Full time salary credit",         "income_salary"),
    ("MONTHLY SALARY",         "Monthly salary payment",          "income_salary"),
    ("PAYROLL TRANSFER",       "Payroll bank transfer",           "income_salary"),
    ("EMPLOYMENT PAYCHECK",    "Employment paycheck",             "income_salary"),
    ("EMPLOYER PAYMENT",       "Employer payment deposit",        "income_salary"),
    ("REGULAR PAY",            "Regular pay deposit",             "income_salary"),

    # income_freelance
    ("STRIPE PAYOUT",          "Stripe transfer payout",          "income_freelance"),
    ("UPWORK LLC",             "Upwork freelance payment",        "income_freelance"),
    ("FIVERR INC",             "Fiverr gig payout",               "income_freelance"),
    ("PAYPAL TRANSFER",        "PayPal business transfer",        "income_freelance"),
    ("VENMO PAYMENT",          "Venmo client payment",            "income_freelance"),
    ("SQUARE CASH",            "Square cash deposit",             "income_freelance"),
    ("ETSY DEPOSIT",           "Etsy seller deposit",             "income_freelance"),
    ("FREELANCE PAYMENT",      "Freelance project payment",       "income_freelance"),
    ("CONSULTING FEE",         "Consulting fee transfer",         "income_freelance"),
    ("CONTRACT PAY",           "Contract work payment",           "income_freelance"),
    ("GIG INCOME",             "Gig income deposit",              "income_freelance"),
    ("TOPTAL PAYOUT",          "Toptal freelance payout",         "income_freelance"),
    ("GURU PAYMENT",           "Guru freelance payment",          "income_freelance"),
    ("1099 INCOME",            "1099 contract income",            "income_freelance"),
    ("INDEPENDENT WORK",       "Independent contractor pay",      "income_freelance"),
    ("PROJECT PAYMENT",        "Project payment received",        "income_freelance"),
    ("CLIENT TRANSFER",        "Client bank transfer",            "income_freelance"),
    ("SIDE INCOME",            "Side hustle income",              "income_freelance"),
    ("DOORDASH EARNINGS",      "DoorDash driver earnings",        "income_freelance"),
    ("UBER DRIVER DEPOSIT",    "Uber driver weekly deposit",      "income_freelance"),
    ("LYFT DRIVER PAY",        "Lyft driver payment",             "income_freelance"),
    ("TASKRABBIT PAY",         "TaskRabbit job payment",          "income_freelance"),
    ("ROVER PAYOUT",           "Rover pet sitting payout",        "income_freelance"),
    ("INSTACART EARNINGS",     "Instacart shopper earnings",      "income_freelance"),
    ("SHOPIFY PAYOUT",         "Shopify store payout",            "income_freelance"),
    ("AMAZON SELLER",          "Amazon seller payment",           "income_freelance"),
    ("EBAY DEPOSIT",           "eBay seller deposit",             "income_freelance"),
    ("TWITCH PAYOUT",          "Twitch creator payout",           "income_freelance"),
    ("YOUTUBE ADSENSE",        "YouTube AdSense payment",         "income_freelance"),
    ("SUBSTACK PAYMENT",       "Substack subscription income",    "income_freelance"),

    # income_government
    ("SOCIAL SECURITY",        "Social security benefit",         "income_government"),
    ("SSA DEPOSIT",            "SSA benefit deposit",             "income_government"),
    ("UNEMPLOYMENT BENEFIT",   "State unemployment benefit",      "income_government"),
    ("IRS TAX REFUND",         "IRS federal tax refund",          "income_government"),
    ("STATE TAX REFUND",       "State tax refund deposit",        "income_government"),
    ("STIMULUS PAYMENT",       "Government stimulus payment",     "income_government"),
    ("EDD BENEFIT",            "EDD unemployment benefit",        "income_government"),
    ("VA BENEFIT",             "VA disability benefit",           "income_government"),
    ("SNAP BENEFIT",           "SNAP food assistance benefit",    "income_government"),
    ("MEDICAID REIMB",         "Medicaid reimbursement",          "income_government"),
    ("GOVERNMENT PENSION",     "Government pension deposit",      "income_government"),
    ("DISABILITY PAYMENT",     "Disability benefit payment",      "income_government"),
    ("WELFARE PAYMENT",        "Welfare assistance payment",      "income_government"),
    ("CHILD SUPPORT",          "Child support payment received",  "income_government"),
    ("HOUSING ASSISTANCE",     "Housing assistance deposit",      "income_government"),
    ("VETERANS BENEFIT",       "Veterans benefit payment",        "income_government"),
    ("FEDERAL BENEFIT",        "Federal benefit deposit",         "income_government"),
    ("STATE BENEFIT",          "State benefit payment",           "income_government"),
    ("TANF PAYMENT",           "TANF assistance payment",         "income_government"),
    ("WORKERS COMP",           "Workers compensation payment",    "income_government"),
    ("FMLA PAYMENT",           "FMLA leave payment",              "income_government"),
    ("PENSION DEPOSIT",        "Pension fund deposit",            "income_government"),
    ("RETIREMENT BENEFIT",     "Government retirement benefit",   "income_government"),
    ("SBA LOAN DEPOSIT",       "SBA small business loan",         "income_government"),
    ("ECONOMIC IMPACT",        "Economic impact payment",         "income_government"),
    ("GRANT PAYMENT",          "Government grant payment",        "income_government"),
    ("PUBLIC ASSISTANCE",      "Public assistance deposit",       "income_government"),
    ("MEDICAID PAYMENT",       "Medicaid payment",                "income_government"),
    ("MEDICARE REFUND",        "Medicare refund",                 "income_government"),
    ("COBRA SUBSIDY",          "COBRA subsidy payment",           "income_government"),

    # income_other
    ("CASHBACK REWARD",        "Credit card cashback reward",     "income_other"),
    ("INTEREST PAYMENT",       "Savings interest payment",        "income_other"),
    ("DIVIDEND DEPOSIT",       "Stock dividend deposit",          "income_other"),
    ("RENTAL INCOME",          "Rental property income",          "income_other"),
    ("INSURANCE REFUND",       "Insurance premium refund",        "income_other"),
    ("BANK BONUS",             "Bank account opening bonus",      "income_other"),
    ("REFERRAL BONUS",         "Referral bonus credit",           "income_other"),
    ("SURVEY PAYMENT",         "Online survey payment",           "income_other"),
    ("GIFT MONEY",             "Gift money deposit",              "income_other"),
    ("SCHOLARSHIP DEPOSIT",    "Scholarship deposit",             "income_other"),
    ("ALIMONY PAYMENT",        "Alimony received",                "income_other"),
    ("SALE PROCEEDS",          "Asset sale proceeds",             "income_other"),
    ("INVESTMENT RETURN",      "Investment return deposit",       "income_other"),
    ("CREDIT REFUND",          "Merchant credit refund",          "income_other"),
    ("PURCHASE REFUND",        "Purchase refund credit",          "income_other"),
    ("WARRANTY CLAIM",         "Warranty claim reimbursement",    "income_other"),
    ("REIMBURSEMENT",          "Expense reimbursement",           "income_other"),
    ("PRIZE WINNINGS",         "Contest prize winnings",          "income_other"),
    ("ROYALTY PAYMENT",        "Royalty payment received",        "income_other"),
    ("SETTLEMENT PAYMENT",     "Legal settlement payment",        "income_other"),
    ("SECURITY DEPOSIT",       "Security deposit returned",       "income_other"),
    ("OVERPAYMENT REFUND",     "Overpayment refund",              "income_other"),
    ("CASHOUT REWARD",         "Rewards cashout",                 "income_other"),
    ("POINTS REDEMPTION",      "Points redemption credit",        "income_other"),
    ("CLASS ACTION",           "Class action settlement",         "income_other"),
    ("TAX CREDIT",             "Tax credit refund",               "income_other"),
    ("MEDICAL REIMB",          "Medical expense reimbursement",   "income_other"),
    ("TRAVEL REIMB",           "Travel reimbursement",            "income_other"),
    ("MISC CREDIT",            "Miscellaneous credit",            "income_other"),
    ("CREDIT ADJUSTMENT",      "Account credit adjustment",       "income_other"),

    # rent_mortgage
    ("PROPERTY MGMT",          "Property management rent",        "rent_mortgage"),
    ("APARTMENT RENT",         "Monthly apartment rent",          "rent_mortgage"),
    ("LANDLORD PAYMENT",       "Rent payment to landlord",        "rent_mortgage"),
    ("LANDLORD ZELLE",         "Zelle payment landlord rent",     "rent_mortgage"),
    ("WELLS FARGO MORTGAGE",   "Wells Fargo mortgage payment",    "rent_mortgage"),
    ("CHASE MORTGAGE",         "Chase home mortgage",             "rent_mortgage"),
    ("BANK OF AMERICA MTGE",   "Bank of America mortgage",        "rent_mortgage"),
    ("QUICKEN LOANS",          "Quicken Loans mortgage",          "rent_mortgage"),
    ("ROCKET MORTGAGE",        "Rocket Mortgage payment",         "rent_mortgage"),
    ("MORTGAGE PAYMENT",       "Monthly mortgage payment",        "rent_mortgage"),
    ("RENT PAYMENT",           "Monthly rent payment",            "rent_mortgage"),
    ("HOUSING PAYMENT",        "Housing payment",                 "rent_mortgage"),
    ("APARTMENT COMPLEX",      "Apartment complex rent",          "rent_mortgage"),
    ("REALTY GROUP",           "Realty group rent payment",       "rent_mortgage"),
    ("PROPERTY RENT",          "Property rent payment",           "rent_mortgage"),
    ("HOME LOAN PAYMENT",      "Home loan monthly payment",       "rent_mortgage"),
    ("LEASE PAYMENT",          "Monthly lease payment",           "rent_mortgage"),
    ("RENTAL PAYMENT",         "Rental payment",                  "rent_mortgage"),
    ("ZILLOW RENT",            "Zillow rental payment",           "rent_mortgage"),
    ("COZY RENT",              "Cozy rental payment",             "rent_mortgage"),
    ("APPFOLIO RENT",          "AppFolio rent payment",           "rent_mortgage"),
    ("BUILDIUM RENT",          "Buildium property management",    "rent_mortgage"),
    ("RENTEC PAYMENT",         "Rentec property payment",         "rent_mortgage"),
    ("STUDENT HOUSING",        "Student housing rent",            "rent_mortgage"),
    ("ROOMMATE RENT",          "Roommate rent share",             "rent_mortgage"),
    ("SUBLEASE PAYMENT",       "Sublease monthly payment",        "rent_mortgage"),
    ("HOMEOWNER ASSOC",        "Homeowners association fee",      "rent_mortgage"),
    ("HOA PAYMENT",            "HOA monthly payment",             "rent_mortgage"),
    ("CONDO FEE",              "Condominium fee",                 "rent_mortgage"),
    ("TOWNHOME RENT",          "Townhome rent payment",           "rent_mortgage"),

    # utilities
    ("ELECTRIC CO",            "Monthly electric bill",           "utilities"),
    ("GAS COMPANY",            "Natural gas utility bill",        "utilities"),
    ("WATER BILL",             "City water and sewer bill",       "utilities"),
    ("INTERNET SERVICE",       "Monthly internet service",        "utilities"),
    ("COMCAST CABLE",          "Comcast cable and internet",      "utilities"),
    ("ATT WIRELESS",           "AT&T wireless bill",              "utilities"),
    ("VERIZON WIRELESS",       "Verizon wireless payment",        "utilities"),
    ("T-MOBILE PAYMENT",       "T-Mobile phone bill",             "utilities"),
    ("XFINITY",                "Xfinity internet cable",          "utilities"),
    ("SPECTRUM INTERNET",      "Spectrum internet bill",          "utilities"),
    ("DUKE ENERGY",            "Duke Energy electric bill",       "utilities"),
    ("PG&E PAYMENT",           "PG&E utility payment",            "utilities"),
    ("CONED PAYMENT",          "ConEd electricity bill",          "utilities"),
    ("ELECTRIC UTILITY",       "Electric utility payment",        "utilities"),
    ("GAS UTILITY",            "Gas utility monthly bill",        "utilities"),
    ("WATER UTILITY",          "Water utility payment",           "utilities"),
    ("TRASH SERVICE",          "Trash and recycling service",     "utilities"),
    ("GARBAGE COLLECTION",     "Garbage collection fee",          "utilities"),
    ("PHONE BILL",             "Monthly phone bill",              "utilities"),
    ("CELL PHONE PAYMENT",     "Cell phone monthly payment",      "utilities"),
    ("HOME PHONE",             "Home phone service",              "utilities"),
    ("LANDLINE BILL",          "Landline telephone bill",         "utilities"),
    ("CABLE TV",               "Cable TV monthly bill",           "utilities"),
    ("SATELLITE TV",           "Satellite TV service",            "utilities"),
    ("DIRECTV",                "DirecTV satellite payment",       "utilities"),
    ("DISH NETWORK",           "Dish Network payment",            "utilities"),
    ("GOOGLE FI",              "Google Fi wireless service",      "utilities"),
    ("MINT MOBILE",            "Mint Mobile phone plan",          "utilities"),
    ("SEWER BILL",             "Sewer utility bill",              "utilities"),
    ("STEAM HEAT",             "Steam heating service",           "utilities"),

    # groceries
    ("WHOLE FOODS",            "Whole Foods grocery purchase",    "groceries"),
    ("TRADER JOES",            "Trader Joe's grocery store",      "groceries"),
    ("KROGER",                 "Kroger supermarket",              "groceries"),
    ("WALMART GROCERY",        "Walmart grocery shopping",        "groceries"),
    ("TARGET GROCERY",         "Target grocery purchase",         "groceries"),
    ("SAFEWAY",                "Safeway grocery store",           "groceries"),
    ("HEB",                    "H-E-B grocery store",             "groceries"),
    ("PUBLIX",                 "Publix supermarket",              "groceries"),
    ("ALDI",                   "ALDI grocery store",              "groceries"),
    ("COSTCO WHOLESALE",       "Costco wholesale grocery",        "groceries"),
    ("SAM'S CLUB",             "Sam's Club grocery",              "groceries"),
    ("WEGMANS",                "Wegmans grocery store",           "groceries"),
    ("STOP & SHOP",            "Stop and Shop grocery",           "groceries"),
    ("GIANT FOOD",             "Giant Food grocery",              "groceries"),
    ("MEIJER",                 "Meijer supermarket",              "groceries"),
    ("SPROUTS",                "Sprouts farmers market",          "groceries"),
    ("FRESH MARKET",           "Fresh Market grocery",            "groceries"),
    ("FOOD LION",              "Food Lion grocery store",         "groceries"),
    ("WINN DIXIE",             "Winn-Dixie grocery",              "groceries"),
    ("HARRIS TEETER",          "Harris Teeter grocery",           "groceries"),
    ("GROCERY STORE",          "Local grocery store",             "groceries"),
    ("SUPERMARKET",            "Supermarket purchase",            "groceries"),
    ("MARKET BASKET",          "Market Basket grocery",           "groceries"),
    ("PIGGLY WIGGLY",          "Piggly Wiggly grocery",           "groceries"),
    ("HANNAFORD",              "Hannaford grocery store",         "groceries"),
    ("SMART & FINAL",          "Smart & Final grocery",           "groceries"),
    ("WIC PURCHASE",           "WIC grocery purchase",            "groceries"),
    ("ORGANIC MARKET",         "Organic market purchase",         "groceries"),
    ("ETHNIC GROCERY",         "International grocery store",     "groceries"),
    ("CORNER STORE",           "Corner store food purchase",      "groceries"),

    # dining_entertainment
    ("MCDONALDS",              "McDonald's fast food",            "dining_entertainment"),
    ("STARBUCKS",              "Starbucks coffee purchase",       "dining_entertainment"),
    ("CHIPOTLE",               "Chipotle Mexican Grill",          "dining_entertainment"),
    ("DOORDASH",               "DoorDash food delivery",          "dining_entertainment"),
    ("UBER EATS",              "Uber Eats delivery",              "dining_entertainment"),
    ("GRUBHUB",                "Grubhub food delivery",           "dining_entertainment"),
    ("RESTAURANTS & BARS",     "Restaurant and bar spending",     "dining_entertainment"),
    ("PIZZA HUT",              "Pizza Hut pizza order",           "dining_entertainment"),
    ("DOMINOS",                "Domino's pizza delivery",         "dining_entertainment"),
    ("TACO BELL",              "Taco Bell fast food",             "dining_entertainment"),
    ("SUBWAY",                 "Subway sandwich shop",            "dining_entertainment"),
    ("PANERA BREAD",           "Panera Bread cafe",               "dining_entertainment"),
    ("CHICK FIL A",            "Chick-fil-A restaurant",          "dining_entertainment"),
    ("DUNKIN",                 "Dunkin' coffee and donuts",       "dining_entertainment"),
    ("LOCAL RESTAURANT",       "Local restaurant dining",         "dining_entertainment"),
    ("SUSHI RESTAURANT",       "Sushi restaurant meal",           "dining_entertainment"),
    ("ITALIAN BISTRO",         "Italian bistro dinner",           "dining_entertainment"),
    ("MOVIE THEATER",          "Movie theater tickets",           "dining_entertainment"),
    ("AMC THEATERS",           "AMC movie theater",               "dining_entertainment"),
    ("CONCERT TICKETS",        "Concert ticket purchase",         "dining_entertainment"),
    ("LIVE NATION",            "Live Nation event tickets",       "dining_entertainment"),
    ("TICKETMASTER",           "Ticketmaster event tickets",      "dining_entertainment"),
    ("BOWLING ALLEY",          "Bowling alley entertainment",     "dining_entertainment"),
    ("MINIATURE GOLF",         "Mini golf entertainment",         "dining_entertainment"),
    ("BAR & GRILL",            "Bar and grill spending",          "dining_entertainment"),
    ("NIGHT CLUB",             "Night club entry and drinks",     "dining_entertainment"),
    ("SPORTS BAR",             "Sports bar and restaurant",       "dining_entertainment"),
    ("FOOD TRUCK",             "Food truck meal",                 "dining_entertainment"),
    ("COFFEE SHOP",            "Coffee shop purchase",            "dining_entertainment"),
    ("BOBA TEA",               "Boba tea shop",                   "dining_entertainment"),

    # transportation
    ("UBER TRIP",              "Uber rideshare trip",             "transportation"),
    ("LYFT RIDE",              "Lyft rideshare ride",             "transportation"),
    ("GASOLINE STATION",       "Gas station fuel purchase",       "transportation"),
    ("SHELL OIL",              "Shell gas station",               "transportation"),
    ("CHEVRON",                "Chevron fuel purchase",           "transportation"),
    ("BP GAS",                 "BP gas station",                  "transportation"),
    ("EXXON",                  "Exxon gas station",               "transportation"),
    ("PARKING METER",          "Parking meter payment",           "transportation"),
    ("METRO TRANSIT",          "Metro public transit",            "transportation"),
    ("BUS PASS",               "Monthly bus pass",                "transportation"),
    ("SUBWAY FARE",            "Subway fare payment",             "transportation"),
    ("TRAIN TICKET",           "Train ticket purchase",           "transportation"),
    ("AMTRAK",                 "Amtrak train ticket",             "transportation"),
    ("GREYHOUND",              "Greyhound bus ticket",            "transportation"),
    ("AIRLINE TICKET",         "Airline ticket purchase",         "transportation"),
    ("UNITED AIRLINES",        "United Airlines flight",          "transportation"),
    ("DELTA AIRLINES",         "Delta Airlines flight",           "transportation"),
    ("SOUTHWEST AIR",          "Southwest Airlines ticket",       "transportation"),
    ("CAR RENTAL",             "Car rental payment",              "transportation"),
    ("ENTERPRISE RENT",        "Enterprise car rental",           "transportation"),
    ("HERTZ RENTAL",           "Hertz car rental",                "transportation"),
    ("TOLL PAYMENT",           "Highway toll payment",            "transportation"),
    ("EZPASS",                 "E-ZPass toll charge",             "transportation"),
    ("PARKING GARAGE",         "Parking garage fee",              "transportation"),
    ("AUTO REPAIR",            "Auto repair service",             "transportation"),
    ("OIL CHANGE",             "Oil change service",              "transportation"),
    ("CAR WASH",               "Car wash service",                "transportation"),
    ("GASOLINE",               "Gasoline fuel purchase",          "transportation"),
    ("ELECTRIC VEHICLE",       "EV charging station",             "transportation"),
    ("BIKE SHARE",             "Bike share rental",               "transportation"),

    # healthcare
    ("CVS PHARMACY",           "CVS pharmacy purchase",           "healthcare"),
    ("WALGREENS",              "Walgreens pharmacy",              "healthcare"),
    ("RITE AID",               "Rite Aid pharmacy",               "healthcare"),
    ("DOCTORS OFFICE",         "Doctor office visit copay",       "healthcare"),
    ("HOSPITAL BILLING",       "Hospital billing payment",        "healthcare"),
    ("DENTAL CARE",            "Dental care payment",             "healthcare"),
    ("VISION CENTER",          "Vision care and glasses",         "healthcare"),
    ("OPTOMETRIST",            "Optometrist eye exam",            "healthcare"),
    ("URGENT CARE",            "Urgent care center visit",        "healthcare"),
    ("EMERGENCY ROOM",         "Emergency room copay",            "healthcare"),
    ("SPECIALIST VISIT",       "Specialist doctor visit",         "healthcare"),
    ("PRESCRIPTION FILL",      "Prescription drug fill",          "healthcare"),
    ("PHARMACY",               "Pharmacy prescription",           "healthcare"),
    ("HEALTH INSURANCE",       "Health insurance premium",        "healthcare"),
    ("MENTAL HEALTH",          "Mental health therapy session",   "healthcare"),
    ("THERAPY SESSION",        "Therapy session payment",         "healthcare"),
    ("CHIROPRACTIC",           "Chiropractic adjustment",         "healthcare"),
    ("PHYSICAL THERAPY",       "Physical therapy session",        "healthcare"),
    ("LABORATORY TEST",        "Medical laboratory test",         "healthcare"),
    ("MEDICAL IMAGING",        "Medical imaging service",         "healthcare"),
    ("HEALTH CLINIC",          "Health clinic visit",             "healthcare"),
    ("TELEHEALTH",             "Telehealth video visit",          "healthcare"),
    ("DERMATOLOGIST",          "Dermatologist visit",             "healthcare"),
    ("GYNECOLOGIST",           "Gynecologist appointment",        "healthcare"),
    ("PEDIATRICIAN",           "Pediatrician visit",              "healthcare"),
    ("HEARING AID",            "Hearing aid purchase",            "healthcare"),
    ("MEDICAL EQUIPMENT",      "Medical equipment purchase",      "healthcare"),
    ("WELLNESS VISIT",         "Annual wellness visit",           "healthcare"),
    ("BLOOD TEST",             "Blood test laboratory",           "healthcare"),
    ("VACCINE PAYMENT",        "Vaccine administration fee",      "healthcare"),

    # debt_payment
    ("VISA CREDIT CARD",       "Visa credit card payment",        "debt_payment"),
    ("MASTERCARD PAYMENT",     "Mastercard credit payment",       "debt_payment"),
    ("STUDENT LOAN",           "Student loan monthly payment",    "debt_payment"),
    ("DISCOVER PAYMENT",       "Discover card payment",           "debt_payment"),
    ("CAPITAL ONE PAYMENT",    "Capital One card payment",        "debt_payment"),
    ("AMERICAN EXPRESS",       "American Express payment",        "debt_payment"),
    ("CHASE CREDIT CARD",      "Chase credit card payment",       "debt_payment"),
    ("CITI CARD PAYMENT",      "Citibank credit card payment",    "debt_payment"),
    ("PERSONAL LOAN",          "Personal loan payment",           "debt_payment"),
    ("AUTO LOAN PAYMENT",      "Auto loan monthly payment",       "debt_payment"),
    ("CAR LOAN",               "Car loan payment",                "debt_payment"),
    ("HOME EQUITY LOAN",       "Home equity loan payment",        "debt_payment"),
    ("HELOC PAYMENT",          "HELOC line of credit payment",    "debt_payment"),
    ("CREDIT LINE PAYMENT",    "Credit line payment",             "debt_payment"),
    ("LOAN PAYMENT",           "Loan monthly payment",            "debt_payment"),
    ("DEBT CONSOLIDATION",     "Debt consolidation payment",      "debt_payment"),
    ("SALLIE MAE",             "Sallie Mae student loan",         "debt_payment"),
    ("NAVIENT",                "Navient student loan payment",    "debt_payment"),
    ("NELNET",                 "Nelnet student loan",             "debt_payment"),
    ("SOFI LOAN",              "SoFi personal loan payment",      "debt_payment"),
    ("LENDING CLUB",           "LendingClub loan payment",        "debt_payment"),
    ("PROSPER LOAN",           "Prosper loan payment",            "debt_payment"),
    ("AFFIRM PAYMENT",         "Affirm BNPL payment",             "debt_payment"),
    ("AFTERPAY",               "Afterpay installment payment",    "debt_payment"),
    ("KLARNA",                 "Klarna payment",                  "debt_payment"),
    ("IRS PAYMENT PLAN",       "IRS installment payment",         "debt_payment"),
    ("MEDICAL DEBT",           "Medical debt payment",            "debt_payment"),
    ("COLLECTIONS PAYMENT",    "Collections agency payment",      "debt_payment"),
    ("JUDGEMENT PAYMENT",      "Court judgment payment",          "debt_payment"),
    ("CREDIT CARD MIN",        "Credit card minimum payment",     "debt_payment"),

    # subscription
    ("NETFLIX",                "Netflix streaming subscription",  "subscription"),
    ("SPOTIFY",                "Spotify music subscription",      "subscription"),
    ("AMAZON PRIME",           "Amazon Prime membership",         "subscription"),
    ("HULU",                   "Hulu streaming subscription",     "subscription"),
    ("ADOBE",                  "Adobe Creative Cloud",            "subscription"),
    ("MICROSOFT 365",          "Microsoft 365 subscription",      "subscription"),
    ("APPLE SUBSCRIPTION",     "Apple subscription service",      "subscription"),
    ("DISNEY PLUS",            "Disney Plus streaming",           "subscription"),
    ("HBO MAX",                "HBO Max subscription",            "subscription"),
    ("PEACOCK",                "Peacock streaming service",       "subscription"),
    ("PARAMOUNT PLUS",         "Paramount Plus streaming",        "subscription"),
    ("YOUTUBE PREMIUM",        "YouTube Premium subscription",    "subscription"),
    ("GOOGLE ONE",             "Google One storage subscription", "subscription"),
    ("ICLOUD STORAGE",         "iCloud storage subscription",     "subscription"),
    ("DROPBOX",                "Dropbox cloud storage",           "subscription"),
    ("GYM MEMBERSHIP",         "Monthly gym membership",          "subscription"),
    ("PLANET FITNESS",         "Planet Fitness membership",       "subscription"),
    ("GOLD'S GYM",             "Gold's Gym membership",           "subscription"),
    ("PELOTON",                "Peloton subscription",            "subscription"),
    ("NYTIMES",                "New York Times subscription",     "subscription"),
    ("LINKEDIN PREMIUM",       "LinkedIn Premium subscription",   "subscription"),
    ("DUOLINGO PLUS",          "Duolingo Plus subscription",      "subscription"),
    ("CALM APP",               "Calm meditation subscription",    "subscription"),
    ("HEADSPACE",              "Headspace meditation app",        "subscription"),
    ("LASTPASS",               "LastPass password manager",       "subscription"),
    ("NORTON SECURITY",        "Norton security subscription",    "subscription"),
    ("MCAFEE",                 "McAfee antivirus subscription",   "subscription"),
    ("AUDIBLE",                "Audible audiobook subscription",  "subscription"),
    ("KINDLE UNLIMITED",       "Kindle Unlimited subscription",   "subscription"),
    ("CRUNCHYROLL",            "Crunchyroll anime subscription",  "subscription"),

    # gambling
    ("DRAFTKINGS",             "DraftKings sports betting",       "gambling"),
    ("FANDUEL",                "FanDuel fantasy sports bet",      "gambling"),
    ("BETMGM",                 "BetMGM sports wagering",          "gambling"),
    ("CASINO RESORT",          "Casino resort gaming",            "gambling"),
    ("LOTTERY TICKET",         "State lottery ticket",            "gambling"),
    ("POKER ROOM",             "Poker room buy-in",               "gambling"),
    ("CAESARS SPORTS",         "Caesars sportsbook bet",          "gambling"),
    ("POINTSBET",              "PointsBet sports wager",          "gambling"),
    ("BARSTOOL SPORTS",        "Barstool sports betting",         "gambling"),
    ("WILLIAM HILL",           "William Hill sports bet",         "gambling"),
    ("BOVADA",                 "Bovada online betting",           "gambling"),
    ("BETWAY",                 "Betway sports wager",             "gambling"),
    ("SLOT MACHINE",           "Casino slot machine",             "gambling"),
    ("BLACKJACK",              "Casino blackjack table",          "gambling"),
    ("SPORTS BETTING",         "Online sports betting",           "gambling"),
    ("FANTASY SPORTS",         "Fantasy sports entry fee",        "gambling"),
    ("HORSE RACING",           "Horse racing bet",                "gambling"),
    ("ONLINE POKER",           "Online poker deposit",            "gambling"),
    ("SCRATCH TICKET",         "Scratch lottery ticket",          "gambling"),
    ("POWERBALL",              "Powerball lottery ticket",        "gambling"),
    ("MEGA MILLIONS",          "Mega Millions lottery",           "gambling"),
    ("BINGO HALL",             "Bingo hall cards",                "gambling"),
    ("RACINO",                 "Racino gaming",                   "gambling"),
    ("TRIBAL CASINO",          "Tribal casino gaming",            "gambling"),
    ("JACKPOT",                "Casino jackpot loss",             "gambling"),
    ("WAGER DEPOSIT",          "Online wager deposit",            "gambling"),
    ("SPORTS WAGER",           "Sports wager placed",             "gambling"),
    ("GAMBLING DEPOSIT",       "Gambling site deposit",           "gambling"),
    ("BET SLIP",               "Bet slip purchase",               "gambling"),
    ("ONLINE CASINO",          "Online casino deposit",           "gambling"),

    # atm_cash
    ("ATM WITHDRAWAL",         "ATM cash withdrawal",             "atm_cash"),
    ("CASH ADVANCE",           "Credit card cash advance",        "atm_cash"),
    ("ATM FEE",                "ATM usage fee",                   "atm_cash"),
    ("CASH WITHDRAWAL",        "Bank cash withdrawal",            "atm_cash"),
    ("ATM DEPOSIT",            "ATM cash deposit",                "atm_cash"),
    ("CASH DEPOSIT",           "Cash deposit at branch",          "atm_cash"),
    ("WITHDRAW CASH",          "Cash withdrawal at ATM",          "atm_cash"),
    ("ATM TRANSACTION",        "ATM transaction",                 "atm_cash"),
    ("BANK ATM",               "Bank ATM withdrawal",             "atm_cash"),
    ("NETWORK ATM",            "Out of network ATM fee",          "atm_cash"),
    ("FOREIGN ATM",            "Foreign ATM withdrawal",          "atm_cash"),
    ("CASH OUT",               "Cash out transaction",            "atm_cash"),
    ("TELLER WITHDRAWAL",      "Bank teller withdrawal",          "atm_cash"),
    ("BRANCH CASH",            "Branch cash withdrawal",          "atm_cash"),
    ("CHECKING CASH OUT",      "Checking account cash out",       "atm_cash"),
    ("SAVINGS WITHDRAWAL",     "Savings account withdrawal",      "atm_cash"),
    ("MONEY ORDER",            "Money order purchase",            "atm_cash"),
    ("CASHIERS CHECK",         "Cashier's check fee",             "atm_cash"),
    ("MONEY GRAM",             "MoneyGram cash pickup",           "atm_cash"),
    ("WESTERN UNION",          "Western Union cash send",         "atm_cash"),
    ("COINSTAR",               "Coinstar coin exchange",          "atm_cash"),
    ("CHECK CASHING",          "Check cashing fee",               "atm_cash"),
    ("PAYDAY LENDER",          "Payday loan cash",                "atm_cash"),
    ("PAWN SHOP",              "Pawn shop cash",                  "atm_cash"),
    ("CASH EXCHANGE",          "Currency exchange",               "atm_cash"),
    ("ATM SURCHARGE",          "ATM surcharge fee",               "atm_cash"),
    ("CASH BACK",              "Debit cash back purchase",        "atm_cash"),
    ("PETTY CASH",             "Petty cash withdrawal",           "atm_cash"),
    ("VAULT CASH",             "Vault cash withdrawal",           "atm_cash"),
    ("CARDLESS ATM",           "Cardless ATM withdrawal",         "atm_cash"),

    # transfer
    ("ZELLE TRANSFER",         "Zelle bank transfer",             "transfer"),
    ("WIRE TRANSFER",          "Domestic wire transfer",          "transfer"),
    ("ACH TRANSFER",           "ACH bank transfer",               "transfer"),
    ("BANK TRANSFER",          "Internal bank transfer",          "transfer"),
    ("VENMO CASHOUT",          "Venmo cashout transfer",          "transfer"),
    ("PAYPAL TRANSFER OUT",    "PayPal bank transfer out",        "transfer"),
    ("INTERBANK TRANSFER",     "Interbank account transfer",      "transfer"),
    ("ACCOUNT TRANSFER",       "Account-to-account transfer",     "transfer"),
    ("SAVINGS TRANSFER",       "Transfer to savings",             "transfer"),
    ("CHECKING TRANSFER",      "Transfer to checking",            "transfer"),
    ("MOBILE TRANSFER",        "Mobile banking transfer",         "transfer"),
    ("ONLINE TRANSFER",        "Online banking transfer",         "transfer"),
    ("SWIFT TRANSFER",         "SWIFT international wire",        "transfer"),
    ("INTERNATIONAL WIRE",     "International wire transfer",     "transfer"),
    ("P2P TRANSFER",           "Peer to peer transfer",           "transfer"),
    ("CASH APP TRANSFER",      "Cash App bank transfer",          "transfer"),
    ("REVOLUT TRANSFER",       "Revolut transfer",                "transfer"),
    ("WISE TRANSFER",          "Wise international transfer",     "transfer"),
    ("FAMILY TRANSFER",        "Family member transfer",          "transfer"),
    ("BUSINESS TRANSFER",      "Business account transfer",       "transfer"),
    ("PAYROLL ADVANCE",        "Payroll advance transfer",        "transfer"),
    ("LOAN PROCEEDS",          "Loan proceeds deposit",           "transfer"),
    ("BALANCE TRANSFER",       "Credit balance transfer",         "transfer"),
    ("OVERDRAFT TRANSFER",     "Overdraft protection transfer",   "transfer"),
    ("LINKED ACCOUNT",         "Linked account transfer",         "transfer"),
    ("INVESTMENT TRANSFER",    "Investment account transfer",     "transfer"),
    ("RETIREMENT TRANSFER",    "Retirement account transfer",     "transfer"),
    ("ESCROW TRANSFER",        "Escrow account transfer",         "transfer"),
    ("TRUST TRANSFER",         "Trust account transfer",          "transfer"),
    ("MEMO TRANSFER",          "Memo payment transfer",           "transfer"),

    # nsf_fee
    ("NSF FEE",                "NSF non-sufficient funds fee",    "nsf_fee"),
    ("OVERDRAFT FEE",          "Overdraft fee charge",            "nsf_fee"),
    ("INSUFFICIENT FUNDS",     "Insufficient funds charge",       "nsf_fee"),
    ("RETURNED ITEM FEE",      "Returned item fee",               "nsf_fee"),
    ("OVERDRAFT PROT FEE",     "Overdraft protection fee",        "nsf_fee"),
    ("BOUNCED CHECK FEE",      "Bounced check fee",               "nsf_fee"),
    ("RETURNED CHECK",         "Returned check fee",              "nsf_fee"),
    ("NSF CHARGE",             "NSF charge bank",                 "nsf_fee"),
    ("OVERDRAFT CHARGE",       "Overdraft charge",                "nsf_fee"),
    ("RETURNED PAYMENT",       "Returned payment fee",            "nsf_fee"),
    ("NONSUFFICIENT FUNDS",    "Non-sufficient funds charge",     "nsf_fee"),
    ("PAID ITEM FEE",          "Paid item overdraft fee",         "nsf_fee"),
    ("UNPAID ITEM FEE",        "Unpaid item fee",                 "nsf_fee"),
    ("CONTINUOUS OD FEE",      "Continuous overdraft fee",        "nsf_fee"),
    ("EXTENDED OD FEE",        "Extended overdraft fee",          "nsf_fee"),
    ("DAILY OD FEE",           "Daily overdraft fee",             "nsf_fee"),
    ("DECLINE FEE",            "Declined transaction fee",        "nsf_fee"),
    ("CHECK RETURN FEE",       "Check return fee",                "nsf_fee"),
    ("ACH RETURN FEE",         "ACH return fee",                  "nsf_fee"),
    ("DEBIT RETURN FEE",       "Debit return fee",                "nsf_fee"),
    ("OVERDRAFT INTEREST",     "Overdraft interest charge",       "nsf_fee"),
    ("NEGATIVE BALANCE FEE",   "Negative balance fee",            "nsf_fee"),
    ("ACCOUNT BELOW ZERO",     "Account below zero fee",          "nsf_fee"),
    ("BANK PENALTY FEE",       "Bank penalty fee",                "nsf_fee"),
    ("OVERDRAFT LINE FEE",     "Overdraft line of credit fee",    "nsf_fee"),
    ("COURTESY PAY FEE",       "Courtesy pay fee",                "nsf_fee"),
    ("COVERED ITEM FEE",       "Covered item fee",                "nsf_fee"),
    ("OD PROTECTION FEE",      "OD protection fee",               "nsf_fee"),
    ("CHARGE BACK FEE",        "Chargeback fee",                  "nsf_fee"),
    ("BANK SERVICE FEE",       "Bank service charge fee",         "nsf_fee"),

    # savings_investment
    ("ROBINHOOD",              "Robinhood investment deposit",    "savings_investment"),
    ("FIDELITY",               "Fidelity investment transfer",    "savings_investment"),
    ("VANGUARD",               "Vanguard fund investment",        "savings_investment"),
    ("CHARLES SCHWAB",         "Charles Schwab investment",       "savings_investment"),
    ("SAVINGS DEPOSIT",        "Savings account deposit",         "savings_investment"),
    ("IRA CONTRIBUTION",       "IRA contribution deposit",        "savings_investment"),
    ("401K CONTRIBUTION",      "401k retirement contribution",    "savings_investment"),
    ("ETRADE",                 "E*Trade investment",              "savings_investment"),
    ("TD AMERITRADE",          "TD Ameritrade investment",        "savings_investment"),
    ("MERRILL LYNCH",          "Merrill Lynch investment",        "savings_investment"),
    ("BETTERMENT",             "Betterment robo-advisor",         "savings_investment"),
    ("WEALTHFRONT",            "Wealthfront investment",          "savings_investment"),
    ("ACORNS",                 "Acorns micro-investment",         "savings_investment"),
    ("STASH INVEST",           "Stash investment app",            "savings_investment"),
    ("M1 FINANCE",             "M1 Finance investment",           "savings_investment"),
    ("COINBASE",               "Coinbase crypto purchase",        "savings_investment"),
    ("BINANCE",                "Binance crypto deposit",          "savings_investment"),
    ("CRYPTO PURCHASE",        "Cryptocurrency purchase",         "savings_investment"),
    ("BITCOIN PURCHASE",       "Bitcoin cryptocurrency buy",      "savings_investment"),
    ("GOLD INVESTMENT",        "Gold investment purchase",        "savings_investment"),
    ("MUTUAL FUND",            "Mutual fund investment",          "savings_investment"),
    ("STOCK PURCHASE",         "Stock purchase",                  "savings_investment"),
    ("BOND PURCHASE",          "Bond investment purchase",        "savings_investment"),
    ("CD PURCHASE",            "Certificate of deposit",          "savings_investment"),
    ("TREASURY BOND",          "Treasury bond purchase",          "savings_investment"),
    ("HIGH YIELD SAVINGS",     "High yield savings deposit",      "savings_investment"),
    ("MONEY MARKET",           "Money market account deposit",    "savings_investment"),
    ("529 PLAN",               "529 education savings",           "savings_investment"),
    ("HSA CONTRIBUTION",       "HSA health savings contribution", "savings_investment"),
    ("ROTH IRA",               "Roth IRA contribution",           "savings_investment"),

    # other
    ("UNKNOWN MERCHANT",       "Unknown merchant purchase",       "other"),
    ("MISC PURCHASE",          "Miscellaneous purchase",          "other"),
    ("MISCELLANEOUS",          "Miscellaneous transaction",       "other"),
    ("POS PURCHASE",           "Point of sale purchase",          "other"),
    ("DEBIT PURCHASE",         "Debit card purchase",             "other"),
    ("GENERAL PURCHASE",       "General retail purchase",         "other"),
    ("ONLINE PURCHASE",        "Online store purchase",           "other"),
    ("RETAIL STORE",           "Retail store purchase",           "other"),
    ("DEPARTMENT STORE",       "Department store shopping",       "other"),
    ("HARDWARE STORE",         "Hardware store purchase",         "other"),
    ("HOME DEPOT",             "Home Depot home improvement",     "other"),
    ("LOWES",                  "Lowe's home improvement",         "other"),
    ("PET STORE",              "Pet store purchase",              "other"),
    ("PETCO",                  "Petco pet supply",                "other"),
    ("PET SUPPLIES",           "Pet supply purchase",             "other"),
    ("CLOTHING STORE",         "Clothing store purchase",         "other"),
    ("SHOES PURCHASE",         "Shoe store purchase",             "other"),
    ("BOOK STORE",             "Bookstore purchase",              "other"),
    ("TOY STORE",              "Toy store purchase",              "other"),
    ("SPORTS GOODS",           "Sporting goods store",            "other"),
    ("HOBBY SHOP",             "Hobby shop purchase",             "other"),
    ("GIFT SHOP",              "Gift shop purchase",              "other"),
    ("FLORIST",                "Florist flower purchase",         "other"),
    ("SALON",                  "Hair salon service",              "other"),
    ("BARBER SHOP",            "Barber shop haircut",             "other"),
    ("SPA SERVICE",            "Spa and wellness service",        "other"),
    ("NAIL SALON",             "Nail salon service",              "other"),
    ("DRY CLEANING",           "Dry cleaning service",            "other"),
    ("LAUNDROMAT",             "Laundromat service",              "other"),
    ("STORAGE UNIT",           "Storage unit rental",             "other"),

    # ---------------------------------------------------------------------------
    # Plaid-format examples — short/mixed-case merchant names, abbreviated
    # descriptions matching actual Plaid sandbox and production naming patterns.
    # ---------------------------------------------------------------------------

    # income_salary (Plaid: payroll via ACH, no clean merchant_name)
    ("",    "ACH Electronic CreditGUSTO PAY 123456",      "income_salary"),
    ("",    "ACH Electronic Credit GUSTO PAY",            "income_salary"),
    ("",    "ACH PAYROLL DEPOSIT ADP",                    "income_salary"),
    ("",    "Direct Dep EMPLOYER PAYROLL",                "income_salary"),
    ("",    "PAYROLL ACH DEPOSIT",                        "income_salary"),
    ("",    "ACH Credit PAYCHEX PAY",                     "income_salary"),
    ("",    "DIRECT DEPOSIT PAYROLL",                     "income_salary"),
    ("",    "ACH Electronic Credit SALARY",               "income_salary"),

    # income_other (Plaid: interest, abbreviated)
    ("",    "INTRST PYMNT",                               "income_other"),
    ("",    "INT EARNED",                                 "income_other"),
    ("",    "INTEREST CREDIT",                            "income_other"),
    ("",    "SAVINGS INTEREST",                           "income_other"),
    ("",    "DIV PAYMENT",                                "income_other"),

    # income_freelance (Plaid: company name payments, Tectra-style)
    ("",    "Tectra Inc",                                 "income_freelance"),
    ("",    "ACH Transfer STRIPE PAYOUT",                 "income_freelance"),
    ("",    "Stripe transfer payout",                     "income_freelance"),
    ("",    "PAYPAL INST XFER",                           "income_freelance"),
    ("",    "Venmo cashout",                              "income_freelance"),

    # debt_payment (Plaid: truncated bank payment descriptions)
    ("",    "CREDIT CARD 3333 PAYMENT *//",               "debt_payment"),
    ("",    "AUTOMATIC PAYMENT - THANK",                  "debt_payment"),
    ("",    "AUTOPAY CREDIT CARD",                        "debt_payment"),
    ("",    "Online Payment Credit Card",                 "debt_payment"),
    ("",    "CHASE CREDIT CRD AUTOPAY",                   "debt_payment"),
    ("",    "STUDENT LOAN PAYMENT",                       "debt_payment"),
    ("",    "AUTO LOAN PMT",                              "debt_payment"),

    # savings_investment (Plaid: CD deposit, investment)
    ("",    "CD DEPOSIT .INITIAL.",                       "savings_investment"),
    ("",    "CD DEPOSIT RENEWAL",                         "savings_investment"),
    ("",    "INVESTMENT PURCHASE",                        "savings_investment"),
    ("",    "Robinhood",                                  "savings_investment"),
    ("",    "FIDELITY BROKERAGE",                         "savings_investment"),

    # transportation (Plaid: short rideshare + airline names)
    ("Uber",          "Uber 063015 SF**POOL**",           "transportation"),
    ("Uber",          "Uber 072515 SF**POOL**",           "transportation"),
    ("Lyft",          "Lyft *ride",                       "transportation"),
    ("United Airlines", "United Airlines",                "transportation"),
    ("Delta",         "Delta Air Lines",                  "transportation"),
    ("Southwest",     "Southwest Airlines",               "transportation"),
    ("",              "SHELL OIL 12345",                  "transportation"),
    ("",              "CHEVRON GAS STATION",              "transportation"),
    ("",              "PARKING LOT",                      "transportation"),
    ("",              "METRO TRANSIT",                    "transportation"),

    # dining_entertainment (Plaid: real brand names, proper case)
    ("McDonald's",    "McDonald's",                       "dining_entertainment"),
    ("Starbucks",     "Starbucks",                        "dining_entertainment"),
    ("KFC",           "KFC",                              "dining_entertainment"),
    ("Chipotle",      "Chipotle Mexican Grill",           "dining_entertainment"),
    ("Domino's Pizza","Domino's Pizza",                   "dining_entertainment"),
    ("Panera Bread",  "Panera Bread",                     "dining_entertainment"),
    ("Dunkin'",       "Dunkin' Donuts",                   "dining_entertainment"),
    ("Taco Bell",     "Taco Bell",                        "dining_entertainment"),
    ("Subway",        "Subway",                           "dining_entertainment"),
    ("Chick-fil-A",   "Chick-fil-A",                      "dining_entertainment"),
    ("",              "Touchstone Climbing",              "dining_entertainment"),

    # other (Plaid: ambiguous merchant names, electronics shops)
    ("FUN",           "SparkFun",                         "other"),
    ("",              "Madison Bicycle Shop",             "other"),
    ("",              "Amazon.com",                       "other"),
    ("Target",        "Target",                           "other"),
    ("Walmart",       "Walmart",                          "other"),
]


def build_training_data() -> tuple[list[Transaction], list[str]]:
    """Convert raw label tuples into Transaction objects + label list."""
    transactions: list[Transaction] = []
    labels: list[str] = []

    for i, (merchant, description, label) in enumerate(RAW_LABELS):
        transactions.append(Transaction(
            transaction_id=f"train_{i:04d}",
            account_id="acc_train",
            user_id="user_train",
            transaction_date=date(2026, 1, 1),
            amount=-100.0,
            merchant_name=merchant,
            description=description,
            plaid_category=[],
            pending=False,
        ))
        labels.append(label)

    return transactions, labels


def main() -> None:
    output_path = Path("models/categorizer.pkl")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"Building training data from {len(RAW_LABELS)} labeled examples…")
    transactions, labels = build_training_data()

    from collections import Counter
    dist = Counter(labels)
    print(f"Category distribution: {dict(sorted(dist.items()))}")

    categorizer = TransactionCategorizer()
    metrics = categorizer.train(transactions, labels)

    print(f"\nTraining complete:")
    print(f"  Accuracy (holdout): {metrics['accuracy']:.1%}")
    print(f"  Train samples: {metrics['n_train']}")
    print(f"  Test samples:  {metrics['n_test']}")

    categorizer.save(output_path)
    print(f"\nModel saved to: {output_path}")
    print("You can now run the full pipeline — categorize_node will load this model.")


if __name__ == "__main__":
    main()
